name: Conan Build

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      build-type:
        required: true
        type: string
      malloc-impl:
        required: true
        type: string
      prerelease:
        required: true
        type: string
      testing:
        required: false
        type: string
        default: 'False'
  workflow_dispatch:
    inputs:
      branch:
        required: true
        type: string
      build-type:
        required: true
        type: choice
        options:
          - Debug
          - Release
          - RelWithDebInfo
      malloc-impl:
        description: 'Allocation Library'
        required: true
        type: choice
        options:
          - libc
          - tcmalloc
          - jemalloc
      prerelease:
        description: 'Fault Instrumentation'
        required: false
        type: choice
        options:
          - 'True'
          - 'False'
        default: 'False'
      testing:
        description: 'Run Tests'
        required: true
        type: choice
        options:
          - 'True'
          - 'False'
        default: 'False'

jobs:
  BuildNuraftMesgDeps:
    runs-on: ubuntu-22.04
    steps:
    - name: Restore Sisl Cache
      id: restore-cache-sisl
      uses: actions/cache/restore@v3
      with:
        path: |
          ~/.conan/data
        key: SislDeps-${{ inputs.build-type }}-${{ inputs.malloc-impl }}-${{ inputs.prerelease }}

    - name: Restore NuraftMesg Cache
      id: restore-cache-nuraftmesg
      uses: actions/cache/restore@v3
      with:
        path: |
          ~/.conan/data
        key: NuMesgDeps-${{ inputs.build-type }}-${{ inputs.malloc-impl }}-${{ inputs.prerelease }}

    - name: Retrieve Code
      uses: actions/checkout@v3
      with:
        path: deps/nuraft_mesg
        ref: ${{ inputs.branch }}
      if: ${{ inputs.testing == 'True' }}

    - name: Retrieve Dependencies
      uses: actions/checkout@v3
      with:
        repository: eBay/sisl
        path: deps/sisl
        ref: master

    - name: Retrieve Recipe
      uses: actions/checkout@v3
      with:
        path: deps/nuraft_mesg
        ref: ${{ inputs.branch }}
      if: ${{ inputs.testing == 'False' && steps.restore-cache-nuraftmesg.outputs.cache-hit != 'true' }}

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
      if: ${{ inputs.testing == 'True' || steps.restore-cache-nuraftmesg.outputs.cache-hit != 'true' }}

    - name: Setup Conan and Export Recipes
      run: |
        python -m pip install --upgrade pip
        python -m pip install conan~=1.0
        conan user
        conan profile new --detect default
        # Set std::string to non-CoW C++11 version
        sed -i 's,compiler.libcxx=libstdc++$,compiler.libcxx=libstdc++11,g' ~/.conan/profiles/default
        conan export deps/sisl oss/master
        conan export deps/nuraft_mesg/3rd_party/nuraft
      if: ${{ inputs.testing == 'True' || steps.restore-cache-nuraftmesg.outputs.cache-hit != 'true' }}

    - name: Build Cache
      run: |
        conan install \
            -o sisl:prerelease=${{ inputs.prerelease }} \
            -o sisl:malloc_impl=${{ inputs.malloc-impl }} \
            -o sisl:testing=False \
            -o testing=False \
            -s build_type=${{ inputs.build-type }} \
            --build missing \
            deps/nuraft_mesg
      if: ${{ inputs.testing != 'True' && steps.restore-cache-nuraftmesg.outputs.cache-hit != 'true' }}

    - name: Test Package
      run: |
        conan create \
            -o sisl:prerelease=${{ inputs.prerelease }} \
            -o sisl:malloc_impl=${{ inputs.malloc-impl }} \
            -o sisl:testing=False \
            -s build_type=${{ inputs.build-type }} \
            --build missing \
            deps/nuraft_mesg
      if: ${{ inputs.testing == 'True' }}

    - name: Cleanup
      run: |
        ls -1d ~/.conan/data/* | grep -Ev '(nuraft|sisl)' | xargs rm -rf
        rm -rf ~/.conan/data/*/*/*/*/build
      if: ${{ steps.restore-cache-nuraftmesg.outputs.cache-hit != 'true' }}

    - name: Save NuraftMesg Cache
      id: save-cache-nuraftmesg
      uses: actions/cache/save@v3
      with:
        path: |
          ~/.conan/data
        key: NuMesgDeps-${{ inputs.build-type }}-${{ inputs.malloc-impl }}-${{ inputs.prerelease }}
      if: ${{ github.event_name != 'pull_request' && steps.restore-cache-nuraftmesg.outputs.cache-hit != 'true' }}
