name: NuraftMesg PR Build

on:
  pull_request:
    branches:
      - main

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        build-type: ["Debug", "Release"]
        malloc-impl: ["libc"]
        prerelease: ["False"]
    uses: ./.github/workflows/build_commit.yml
    with:
      branch: ${{ github.ref }}
      build-type: ${{ matrix.build-type }}
      malloc-impl: ${{ matrix.malloc-impl }}
      prerelease: ${{ matrix.prerelease }}
      testing: 'True'
